# Generated by Django 4.2.3 on 2023-07-04 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_partido_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='imagenes/logos-partidos/'),
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, max_length=255, null=True, upload_to='imagenes/fotos-candidatos/')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.partido')),
            ],
        ),
    ]
