# Generated by Django 4.2.3 on 2023-07-04 14:36

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_partido_logo_candidato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='foto',
            field=sorl.thumbnail.fields.ImageField(blank=True, max_length=255, null=True, upload_to='imagenes/fotos-candidatos/'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, max_length=255, null=True, upload_to='imagenes/logos-partidos/'),
        ),
    ]
