# Generated by Django 4.2.3 on 2023-07-04 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_country_region_alter_eleccion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoelecto',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.city'),
        ),
        migrations.AddField(
            model_name='cargoelecto',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.country'),
        ),
        migrations.AddField(
            model_name='cargoelecto',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.region'),
        ),
    ]
