# Generated by Django 4.2.3 on 2023-07-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cargoelecto_localidad_cargoelecto_pais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoelecto',
            name='cant_votos',
            field=models.IntegerField(default=0),
        ),
    ]
