# Generated by Django 4.2.3 on 2023-07-04 16:58

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cargoelecto_cant_votos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoelecto',
            name='localidad',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='provincia', chained_model_field='region', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.city'),
        ),
        migrations.AlterField(
            model_name='cargoelecto',
            name='pais',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.country', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='cargoelecto',
            name='provincia',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='pais', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.region'),
        ),
    ]
