# Generated by Django 4.2.3 on 2023-07-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_cargoelecto_localidad_alter_cargoelecto_pais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoelecto',
            name='ult_actualizacion',
            field=models.DateField(auto_now=True),
        ),
    ]
