# Generated by Django 4.2.3 on 2023-07-04 17:22

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_cargoelecto_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='partido', unique=True),
            preserve_default=False,
        ),
    ]
