# Generated by Django 4.2.3 on 2023-07-04 17:23

import autoslug.fields
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_partido_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='nombre', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='foto',
            field=sorl.thumbnail.fields.ImageField(default=None, max_length=255, upload_to='imagenes/fotos-candidatos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partido',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(default=None, max_length=255, upload_to='imagenes/logos-partidos/'),
            preserve_default=False,
        ),
    ]
